# Generated by Django 4.2.11 on 2024-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="work_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="workout",
            name="work_video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
