# Generated by Django 4.2.11 on 2024-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="routine_info",
            field=models.ManyToManyField(
                related_name="routines", to="routine.routineinfo"
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="created_by",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="routine",
            name="updated_by",
            field=models.CharField(max_length=50),
        ),
    ]
