# Generated by Django 4.2.11 on 2024-04-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_routine_routine_info_alter_routine_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routine",
            name="routine_info",
        ),
    ]
