# Generated by Django 4.2.11 on 2024-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0003_remove_routine_routine_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routine",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="routineinfo",
            old_name="routine_id",
            new_name="routine",
        ),
        migrations.RenameField(
            model_name="routineinfo",
            old_name="workout_id",
            new_name="workout",
        ),
    ]
