# Generated by Django 3.0.4 on 2024-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='work_date',
            field=models.DateField(),
        ),
    ]
